CREATE TABLE IF NOT EXISTS `import_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file_name` varchar(255) NOT NULL,
  `store_id` int(11) NOT NULL,
  `price_category_id` int(11) NOT NULL,
  `supplier_id` int(11) NOT NULL,
  `total_records` int(11) NOT NULL DEFAULT '0',
  `successful_records` int(11) NOT NULL DEFAULT '0',
  `failed_records` int(11) NOT NULL DEFAULT '0',
  `error_log` text,
  `status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
  `created_by` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `import_history_store_id_foreign` (`store_id`),
  KEY `import_history_price_category_id_foreign` (`price_category_id`),
  KEY `import_history_supplier_id_foreign` (`supplier_id`),
  KEY `import_history_created_by_foreign` (`created_by`),
  CONSTRAINT `import_history_store_id_foreign` FOREIGN KEY (`store_id`) REFERENCES `inv_stores` (`id`),
  CONSTRAINT `import_history_price_category_id_foreign` FOREIGN KEY (`price_category_id`) REFERENCES `price_categories` (`id`),
  CONSTRAINT `import_history_supplier_id_foreign` FOREIGN KEY (`supplier_id`) REFERENCES `inv_suppliers` (`id`),
  CONSTRAINT `import_history_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;